services:
  - type: web
    name: dashboard-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: LLM_MODEL
        value: gpt-5-mini-2025-08-07
      - key: LOG_LEVEL
        value: info
